# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-06T04:05:22+00:00

from __future__ import annotations

from datetime import date
from enum import Enum, StrEnum
from typing import Any
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    EmailStr,
    Field,
    SecretStr,
    confloat,
    conint,
    constr,
)


class ApiResponseGeneric(BaseModel):
    data: Any = Field(..., description='實際載荷，由各 endpoint 具體化')
    message: str | None = None


class ApiFieldError(BaseModel):
    field: str
    message: str


class CursorPage(BaseModel):
    items: list[Any]
    next_cursor: str | None = None
    has_more: bool
    total_count: int | None = None


class LoginRequest(BaseModel):
    email: EmailStr
    password: SecretStr


class TokenType(StrEnum):
    Bearer = 'Bearer'


class Data(BaseModel):
    access_token: str
    refresh_token: str = Field(..., description='用於 /auth/refresh 換發 access token')
    token_type: TokenType
    expires_in: int = Field(..., description='access_token 有效秒數')


class LoginResponse(ApiResponseGeneric):
    data: Data | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class ConversationStatus(StrEnum):
    active = 'active'
    waiting_human = 'waiting_human'
    closed = 'closed'


class ResolutionLayer(Enum):
    case_library = 'case_library'
    rag = 'rag'
    human = 'human'
    NoneType_None = None


class Conversation(BaseModel):
    id: UUID
    document_number: constr(max_length=30) | None = Field(
        None, description='ServiceTicket 編號 ST-YYYYMMDD-NNNN（ERP 引用號）'
    )
    line_user_id: str
    display_name: str
    status: ConversationStatus
    resolution_layer: ResolutionLayer | None = None
    message_count: conint(ge=0)
    created_at: AwareDatetime
    updated_at: AwareDatetime


class ConversationEnvelope(ApiResponseGeneric):
    data: Conversation | None = Field(
        None, description='實際載荷，由各 endpoint 具體化'
    )


class ConversationPage(CursorPage):
    items: list[Conversation] | None = None


class ProblemCardStatus(StrEnum):
    draft = 'draft'
    confirmed = 'confirmed'
    resolved = 'resolved'


class Urgency(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class ProblemCard(BaseModel):
    id: UUID
    conversation_id: UUID
    brand: constr(max_length=50)
    model: constr(max_length=100)
    symptom: constr(max_length=1000)
    category: str
    urgency: Urgency
    confidence_score: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='AI 分類信心分數（閾值 0.6 以下觸發人工覆核）'
    )
    status: ProblemCardStatus
    media_urls: list[AnyUrl] | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime
    # CR-0022/ADR-0112：問題卡來源 + AI 草擬待補欄位 hint（optional，反相容；regen 後須重加）
    source: str | None = None
    ai_missing_fields: list[str] | None = None


class ProblemCardPage(CursorPage):
    items: list[ProblemCard] | None = None


class WorkOrderStatus(StrEnum):
    inquiring = 'inquiring'
    qualified = 'qualified'
    quoted = 'quoted'
    negotiating = 'negotiating'
    accepted = 'accepted'
    scheduled = 'scheduled'
    dispatching = 'dispatching'
    assigned = 'assigned'
    en_route = 'en_route'
    arrived = 'arrived'
    in_progress = 'in_progress'
    completed = 'completed'
    billed = 'billed'
    paid = 'paid'
    closed = 'closed'
    cancelled = 'cancelled'


class WorkOrder(BaseModel):
    id: UUID
    document_number: constr(max_length=30) | None = Field(
        None, description='WorkOrder 編號 WO-YYYYMMDD-NNNN（ERP 引用號）'
    )
    problem_card_id: UUID
    technician_id: UUID | None = None
    status: WorkOrderStatus
    district: str
    address: str
    brand: str
    model: str
    urgency: Urgency
    estimated_reward: constr(pattern=r'^-?\d+(\.\d{1,2})?$') | None = Field(
        None, description='Decimal(10,2) 序列化為字串以避免 JS 浮點誤差'
    )
    scheduled_time: AwareDatetime | None = None
    actual_arrival: AwareDatetime | None = None
    completion_time: AwareDatetime | None = None
    version: int | None = Field(None, description='樂觀鎖版本號，更新時 server 比對')
    created_at: AwareDatetime
    updated_at: AwareDatetime
    # CR-0026 公單標準化欄位（全 Optional，向後相容；對應 migration 036）
    service_category: str | None = Field(None, description='install/warranty_in/warranty_out/repair')
    problem_type: str | None = None
    serial_number: str | None = None
    door_type: str | None = None
    door_thickness: str | None = None
    is_interior_door: bool | None = None
    warranty_status: str | None = Field(None, description='in_warranty/out_warranty/not_applicable')
    purchase_date: str | None = Field(None, description='購買日 ISO date')
    invoice_no: str | None = None
    completion_status: str | None = Field(
        None,
        description='M05 Q052 六段：pending_report/pending_photos/pending_customer_confirm/'
                    'pending_cs_review/completed/closed',
    )
    status_reason: str | None = Field(None, description='狀態變更原因（cancel/reopen/reschedule 必填）')
    parent_work_order_id: UUID | None = Field(None, description='返修/reopen 連回原工單')
    customer_final_amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$') | None = Field(
        None, description='對外單一最終金額（客戶端電子工單只露此值）'
    )
    # CR-0043 Phase 2（全 Optional，向後相容；對應 migration 052）
    customer_name: str | None = Field(None, description='客戶姓名（M1.1，接回 response）')
    customer_phone: str | None = Field(None, description='聯絡電話（M1.2，接回 response）')
    dealer: str | None = Field(None, description='M2.3 購買地點/經銷商')
    install_date: str | None = Field(None, description='M2.4 安裝日期 ISO date')
    rain_exposure: str | None = Field(
        None, description='M2.5 indoor/outdoor_covered/outdoor_exposed'
    )
    special_door_surcharge: bool | None = Field(None, description='M4.1 特殊門型加價確認')
    payment_method: str | None = Field(
        None, description='M5.5 cash/bank_transfer/credit_card/line_pay'
    )


class WorkOrderEnvelope(ApiResponseGeneric):
    data: WorkOrder | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class WorkOrderPage(CursorPage):
    items: list[WorkOrder] | None = None


class PartsUsedItem(BaseModel):
    part_id: UUID
    quantity: conint(ge=1)


class CompletionReport(BaseModel):
    summary: constr(max_length=2000)
    photos_before: list[AnyUrl] | None = None
    photos_after: list[AnyUrl] | None = None
    parts_used: list[PartsUsedItem] | None = None
    actual_amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$') | None = None


class WorkOrderCancelRequest(BaseModel):
    reason: constr(max_length=500) | None = None


class ReasonCode(StrEnum):
    auto_dispatch_exhausted = 'auto_dispatch_exhausted'
    customer_requested_specific_tech = 'customer_requested_specific_tech'
    skill_shortage_override = 'skill_shortage_override'
    sla_rescue = 'sla_rescue'
    other = 'other'


class OverrideFlags(BaseModel):
    allow_circuit: bool | None = False
    allow_cross_area: bool | None = False


class WorkOrderAssignRequest(BaseModel):
    technician_id: UUID
    reason_code: ReasonCode
    reason_text: constr(max_length=500) | None = None
    override_flags: OverrideFlags | None = None


class Level(StrEnum):
    operations_manager = 'operations_manager'
    tenant_admin = 'tenant_admin'


class WorkOrderEscalateRequest(BaseModel):
    level: Level
    reason: constr(max_length=500)


class WarrantyClaimStatus(StrEnum):
    filed = 'filed'
    approved = 'approved'
    rejected = 'rejected'
    in_progress = 'in_progress'
    closed = 'closed'


class WarrantyClaim(BaseModel):
    id: UUID
    document_number: constr(max_length=30) | None = Field(
        None, description='WarrantyClaim 編號 WC-YYYYMMDD-NNNN（ERP 引用號）'
    )
    work_order_id: UUID | None = None
    customer_id: UUID
    device_brand: str
    device_model: str
    purchase_date: date | None = None
    warranty_start_date: date = Field(
        ..., description='保固起始日（以「交屋日期」為準）'
    )
    warranty_end_date: date
    claim_date: date
    is_within_warranty: bool
    status: WarrantyClaimStatus
    dispute_reason: str | None = None
    verification_source: str | None = None
    resolution: str | None = None
    discount_offered: constr(pattern=r'^-?\d+(\.\d{1,2})?$') | None = Field(
        None, description='折讓金額（無保固但提供折讓時）'
    )
    created_at: AwareDatetime
    updated_at: AwareDatetime


class WarrantyClaimEnvelope(ApiResponseGeneric):
    data: WarrantyClaim | None = Field(
        None, description='實際載荷，由各 endpoint 具體化'
    )


class WarrantyClaimPage(CursorPage):
    items: list[WarrantyClaim] | None = None


class Decision(StrEnum):
    approve = 'approve'
    reject = 'reject'
    start_review = 'start_review'


class WarrantyDecision(BaseModel):
    decision: Decision
    resolution: constr(max_length=500) | None = Field(
        None, description='處理結果描述（approve / reject 必填）'
    )
    discount_offered: constr(pattern=r'^-?\d+(\.\d{1,2})?$') | None = Field(
        None,
        description='折讓金額（百分比或金額，由業務語意自行解讀；僅 approve 時生效）',
    )


class RefundRequestStatus(StrEnum):
    pending = 'pending'
    csm_approved = 'csm_approved'
    approved = 'approved'
    rejected = 'rejected'
    escalated = 'escalated'
    executed = 'executed'
    cancelled = 'cancelled'


class RefundRequest(BaseModel):
    id: UUID
    document_number: constr(max_length=30) | None = Field(
        None, description='RefundMemo 編號 RM-YYYYMMDD-NNNN（ERP 引用號）'
    )
    work_order_id: UUID
    invoice_id: UUID | None = None
    complaint_id: UUID | None = None
    requested_by: UUID
    amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$')
    reason: str
    status: RefundRequestStatus
    requires_dual_sign: bool | None = None
    approval_chain: list[dict[str, Any]] | None = Field(
        None, description='審批鏈（已記錄的決策步驟，順序由舊到新）'
    )
    executed_at: AwareDatetime | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class RefundRequestEnvelope(ApiResponseGeneric):
    data: RefundRequest | None = Field(
        None, description='實際載荷，由各 endpoint 具體化'
    )


class RefundRequestPage(CursorPage):
    items: list[RefundRequest] | None = None


class DisputeType(StrEnum):
    pricing = 'pricing'
    quality = 'quality'
    warranty = 'warranty'
    cancellation_fee = 'cancellation_fee'
    settlement = 'settlement'


class DisputeStatus(StrEnum):
    filed = 'filed'
    in_review = 'in_review'
    resolved = 'resolved'
    rejected = 'rejected'
    closed = 'closed'


class Dispute(BaseModel):
    id: UUID
    work_order_id: UUID | None = None
    invoice_id: UUID | None = None
    filed_by: UUID
    dispute_type: DisputeType
    status: DisputeStatus
    description: str
    evidence: dict[str, Any] | list[dict[str, Any]] | None = Field(
        None, description='雙方證據（jsonb；通常為 customer/technician 兩段結構）'
    )
    resolution: str | None = None
    resolution_amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$') | None = Field(
        None, description='調解金額（部分退款 / 全額退款時填寫）'
    )
    resolved_by: UUID | None = None
    filed_at: AwareDatetime
    resolved_at: AwareDatetime | None = None
    sla_deadline: AwareDatetime | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class DisputeEnvelope(ApiResponseGeneric):
    data: Dispute | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class DisputePage(CursorPage):
    items: list[Dispute] | None = None


class Decision1(StrEnum):
    approve = 'approve'
    reject = 'reject'
    escalate = 'escalate'


class RefundDecision(BaseModel):
    decision: Decision1
    reason: constr(max_length=500)
    dual_sign_required: bool | None = Field(
        None, description='金額門檻以上需第二簽核者'
    )


class RefundEnvelope(ApiResponseGeneric):
    pass


class SignaturePayload(BaseModel):
    customer_signature: str = Field(..., description='Base64 編碼的簽章影像或 SVG Path')
    technician_signature: str
    gps_lat: float | None = None
    gps_lng: float | None = None
    signed_at: AwareDatetime | None = None


class DispatchAction(StrEnum):
    assign = 'assign'
    accept = 'accept'
    reject = 'reject'
    timeout = 'timeout'
    reassign = 'reassign'
    cancel = 'cancel'


class DispatchLog(BaseModel):
    id: UUID
    work_order_id: UUID
    action: DispatchAction
    technician_id: UUID | None = None
    technician_name: str | None = Field(
        None, description='由 technicians 表 JOIN 取得方便前端顯示'
    )
    match_score: float | None = Field(None, description='AI 媒合分數（0-100）')
    match_factors: dict[str, Any] | None = Field(
        None,
        description='媒合因子（jsonb；通常為 distance/skill/availability 加權結構）',
    )
    rejection_reason: str | None = None
    timeout_seconds: int | None = None
    notes: str | None = None
    created_at: AwareDatetime


class DispatchLogPage(CursorPage):
    items: list[DispatchLog] | None = None


class DispatchQueueSnapshot(BaseModel):
    pending: int
    assigning: int
    assigned: int
    sla_at_risk: int | None = Field(None, description='2 小時內可能逾期的工單數')


class QuoteStatus(StrEnum):
    draft = 'draft'
    sent = 'sent'
    negotiating = 'negotiating'
    accepted = 'accepted'
    rejected = 'rejected'
    expired = 'expired'


class Currency(StrEnum):
    TWD = 'TWD'


class ItemType(StrEnum):
    labor = 'labor'
    parts = 'parts'
    travel = 'travel'
    holiday_surcharge = 'holiday_surcharge'
    appearance_change = 'appearance_change'
    other = 'other'


class BreakdownItem(BaseModel):
    item_type: ItemType
    description: constr(max_length=200)
    amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$')


class ProposedBy(StrEnum):
    system = 'system'
    customer = 'customer'
    technician = 'technician'
    admin = 'admin'


class Outcome(StrEnum):
    pending = 'pending'
    accepted = 'accepted'
    rejected = 'rejected'
    counter_offered = 'counter_offered'


class NegotiationHistoryItem(BaseModel):
    round: conint(ge=1) | None = None
    proposed_by: ProposedBy | None = None
    proposed_amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$') | None = None
    proposed_at: AwareDatetime | None = None
    outcome: Outcome | None = None


class Quote(BaseModel):
    id: UUID
    work_order_id: UUID
    status: QuoteStatus
    min_amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$') = Field(
        ..., description='Decimal(10,2) 字串，對應區間下限'
    )
    max_amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$')
    currency: Currency
    final_amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$') | None = Field(
        None, description='客戶 accept 後的最終金額'
    )
    breakdown: list[BreakdownItem] | None = Field(None, description='報價明細項')
    valid_until: AwareDatetime = Field(..., description='有效期（預設 48h）')
    negotiation_history: list[NegotiationHistoryItem] | None = Field(
        None, description='議價輪次記錄'
    )
    version: int = Field(..., description='樂觀鎖')
    created_at: AwareDatetime
    updated_at: AwareDatetime


class QuoteEnvelope(ApiResponseGeneric):
    data: Quote | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class ExceptionType(StrEnum):
    no_show = 'no_show'
    customer_absent = 'customer_absent'
    scope_change_rejected = 'scope_change_rejected'
    material_shortage = 'material_shortage'
    delay_severe = 'delay_severe'
    appearance_refused = 'appearance_refused'
    payment_failed = 'payment_failed'
    quality_complaint = 'quality_complaint'
    schedule_conflict = 'schedule_conflict'
    other = 'other'


class ExceptionStatus(StrEnum):
    open = 'open'
    investigating = 'investigating'
    resolved = 'resolved'
    escalated = 'escalated'
    closed = 'closed'


class Severity(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class ActorType(StrEnum):
    customer = 'customer'
    technician = 'technician'
    system = 'system'
    admin = 'admin'


class Actor(BaseModel):
    actor_type: ActorType | None = None
    actor_id: str | None = None


class Exception(BaseModel):
    id: UUID
    work_order_id: UUID
    exception_type: ExceptionType
    status: ExceptionStatus
    severity: Severity
    description: constr(max_length=2000) | None = None
    return_to_stage: str | None = Field(
        None, description='異常處理後工單應返回的 WorkOrder 狀態'
    )
    triggers_circuit_breaker: bool | None = Field(
        None, description='是否觸發技師熔斷計數（24hr 3 次或 12 月 3 次放鴿子）'
    )
    actor: Actor | None = None
    resolution: str | None = Field(None, description='處理結果描述')
    resolved_at: AwareDatetime | None = None
    resolved_by: UUID | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None


class ExceptionEnvelope(ApiResponseGeneric):
    data: Exception | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class ExceptionPage(CursorPage):
    items: list[Exception] | None = None


class InvoiceStatus(StrEnum):
    pending = 'pending'
    issued = 'issued'
    allowance_pending = 'allowance_pending'
    voided = 'voided'
    reopened = 'reopened'


class TaxType(StrEnum):
    taxable = 'taxable'
    zero_rated = 'zero_rated'
    exempt = 'exempt'


class Category(StrEnum):
    service_fee = 'service_fee'
    travel_fee = 'travel_fee'
    parts = 'parts'
    other = 'other'


class Invoice(BaseModel):
    id: UUID
    work_order_id: UUID
    invoice_number: constr(pattern=r'^[A-Z]{2}\d{8}$') = Field(
        ..., description='台灣電子發票號碼（如 AB12345678）'
    )
    tax_id: constr(pattern=r'^\d{8}$') | None = Field(
        None, description='買方統編（選填）'
    )
    amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$')
    tax_type: TaxType | None = 'taxable'
    status: InvoiceStatus
    issued_at: AwareDatetime
    voided_at: AwareDatetime | None = None
    void_reason: str | None = None
    allowance_amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$') | None = Field(
        None, description='折讓金額（退款時部分折讓）'
    )
    category: Category | None = Field(
        None, description='稅務分類 — 車馬費獨立開立，不與工單合併'
    )
    reopened_from: UUID | None = Field(None, description='重開發票的原發票 ID')
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None


class InvoiceEnvelope(ApiResponseGeneric):
    data: Invoice | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class InvoicePage(CursorPage):
    items: list[Invoice] | None = None


class TechnicianLevel(StrEnum):
    S = 'S'
    A = 'A'
    B = 'B'
    C = 'C'


class TechnicianAvailability(StrEnum):
    available = 'available'
    busy = 'busy'
    offline = 'offline'
    on_leave = 'on_leave'
    circuit_breaker_open = 'circuit_breaker_open'


class Technician(BaseModel):
    id: UUID
    name: str
    phone: constr(pattern=r'^09\d{8}$')
    level: TechnicianLevel
    availability: TechnicianAvailability
    skills: list[str] = Field(..., description='可服務品牌 / 技能碼清單')
    service_areas: list[str] = Field(..., description='服務區域代碼（行政區）')
    rating: confloat(ge=0.0, le=5.0)
    completed_orders_count: conint(ge=0) | None = None
    circuit_breaker_until: AwareDatetime | None = None
    created_at: AwareDatetime


class TechnicianEnvelope(ApiResponseGeneric):
    data: Technician | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class TechnicianPage(CursorPage):
    items: list[Technician] | None = None


class ScheduleRequestBody(BaseModel):
    start_date: date
    end_date: date
    reason: constr(min_length=5, max_length=500)


class Type(StrEnum):
    leave = 'leave'
    standby = 'standby'


class Status(StrEnum):
    pending = 'pending'
    approved = 'approved'
    rejected = 'rejected'
    cancelled = 'cancelled'


class ScheduleRequest(BaseModel):
    id: UUID
    type: Type
    start_date: date
    end_date: date
    reason: str
    status: Status
    created_at: AwareDatetime
    resolved_at: AwareDatetime | None = None
    resolution_note: str | None = None


class AdminScheduleRequest(ScheduleRequest):
    technician_user_id: UUID
    technician_name: str | None = None


class EventType(StrEnum):
    scope_change = 'scope_change'
    material_request = 'material_request'
    delay = 'delay'
    door_check = 'door_check'
    signature_submitted = 'signature_submitted'
    reschedule_proposed = 'reschedule_proposed'
    other = 'other'


class WorkOrderEvent(BaseModel):
    id: UUID
    event_type: EventType
    payload: dict[str, Any] = Field(..., description='事件型別專屬 payload')
    actor_user_id: UUID | None = None
    created_at: AwareDatetime


class Purpose(StrEnum):
    door_check_before = 'door_check_before'
    door_check_after = 'door_check_after'
    completion_before = 'completion_before'
    completion_after = 'completion_after'
    dispute_evidence_customer = 'dispute_evidence_customer'
    dispute_evidence_technician = 'dispute_evidence_technician'
    other = 'other'


class MediaFile(BaseModel):
    id: UUID
    url: str = Field(..., description='相對路徑 /api/v1/media/{id}')
    filename: str
    content_type: str
    size_bytes: int
    purpose: Purpose
    work_order_id: UUID | None = None
    dispute_id: UUID | None = None
    sha256: str | None = None
    created_at: AwareDatetime


class Customer(BaseModel):
    id: UUID
    display_name: str = Field(
        ..., description='顯示名稱（LINE 名稱或從電話 / userId 推導）'
    )
    line_user_id: str | None = Field(
        None,
        description='LINE Platform User ID（U + 32 hex），可能為空（非 LINE 來源）',
    )
    phone: str | None = None
    email: EmailStr | None = None
    address: str | None = None
    last_active_at: AwareDatetime | None = Field(
        None, description='最近一次互動時間（users.last_active_at）'
    )
    total_conversations: conint(ge=0)
    total_orders: conint(ge=0) = Field(
        ...,
        description='此客戶累積工單數（穿越 conversations → problem_cards → work_orders）',
    )
    last_service_at: AwareDatetime | None = Field(
        None, description='最近一次工單完工時間'
    )
    created_at: AwareDatetime


class CustomerEnvelope(ApiResponseGeneric):
    data: Customer | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class CustomerPage(CursorPage):
    items: list[Customer] | None = None


class CustomerCreateRequest(BaseModel):
    display_name: constr(min_length=1, max_length=255)
    phone: constr(max_length=50) | None = None
    email: EmailStr | None = None
    address: str | None = None
    line_user_id: constr(max_length=255) | None = None


class CustomerUpdateRequest(BaseModel):
    """PUT 整體取代；未提供的欄位視為 null（display_name 必填）。"""

    display_name: constr(min_length=1, max_length=255)
    phone: constr(max_length=50) | None = None
    email: EmailStr | None = None
    address: str | None = None


class RoleResource(StrEnum):
    work_orders = 'work_orders'
    technicians = 'technicians'
    customers = 'customers'
    accounting = 'accounting'
    invoices = 'invoices'
    refunds = 'refunds'
    inventory = 'inventory'
    warranty = 'warranty'
    disputes = 'disputes'
    audit_logs = 'audit_logs'
    roles = 'roles'
    system_settings = 'system_settings'


class RolePermission(BaseModel):
    resource: RoleResource
    read: bool
    write: bool
    delete: bool
    locked: bool | None = Field(
        False, description='是否為系統強制鎖定的權限（不可被自訂角色覆寫）'
    )


class Role(BaseModel):
    id: str = Field(
        ...,
        description='角色 ID（system roles 為固定字串：admin / reviewer / technician / brand_oem / line_user）',
    )
    name: str
    description: str
    user_count: conint(ge=0) = Field(..., description='本租戶內擁有此角色的使用者數')
    is_system: bool = Field(..., description='是否為系統內建角色（不可刪除）')
    permissions: list[RolePermission]


class RolesEnvelope(ApiResponseGeneric):
    data: list[Role] | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class InventoryStockStatus(StrEnum):
    in_stock = 'in_stock'
    low_stock = 'low_stock'
    out_of_stock = 'out_of_stock'


class InventoryItem(BaseModel):
    id: UUID
    part_number: str = Field(..., description='料號（unique；例：BAT-AA-001）')
    name: str
    category: str = Field(
        ...,
        description='類別（battery / lock_body / circuit_board / screw / side_panel / other）',
    )
    brand_compatibility: list[str] | None = Field(None, description='適用品牌清單')
    unit_cost: constr(pattern=r'^-?\d+(\.\d{1,2})?$') | None = Field(
        None, description='單位成本（TWD，decimal 字串；NULL 表示未設定）'
    )
    quantity_on_hand: conint(ge=0)
    reorder_point: conint(ge=0) = Field(
        ..., description='安全庫存量；quantity_on_hand <= reorder_point 觸發補貨警示'
    )
    stock_status: InventoryStockStatus
    supplier: str | None = None
    is_active: bool
    last_restocked_at: AwareDatetime | None = Field(
        None,
        description='最近一次入庫時間（衍生自 inventory_transactions purchase 紀錄；NULL 表示尚未補貨過）',
    )
    created_at: AwareDatetime
    updated_at: AwareDatetime


class InventoryItemPage(CursorPage):
    items: list[InventoryItem] | None = None


class InventoryItemEnvelope(ApiResponseGeneric):
    data: InventoryItem | None = Field(
        None, description='實際載荷，由各 endpoint 具體化'
    )


class NotificationType(StrEnum):
    work_order = 'work_order'
    refund = 'refund'
    dispute = 'dispute'
    rbac = 'rbac'
    inventory = 'inventory'
    sla = 'sla'
    system = 'system'
    mention = 'mention'


class NotificationSeverity(StrEnum):
    info = 'info'
    warning = 'warning'
    critical = 'critical'


class Source(StrEnum):
    websocket = 'websocket'
    line_push = 'line_push'
    system = 'system'
    email_fallback = 'email_fallback'


class RelatedEntity(BaseModel):
    type: str | None = None
    id: UUID | None = None
    url: AnyUrl | None = None


class Method(StrEnum):
    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'


class Action(BaseModel):
    label: str | None = None
    endpoint: str | None = None
    method: Method | None = None


class Notification(BaseModel):
    id: UUID
    type: NotificationType
    severity: NotificationSeverity
    title: constr(max_length=200)
    body: constr(max_length=1000)
    source: Source
    created_at: AwareDatetime
    read_at: AwareDatetime | None = None
    archived_at: AwareDatetime | None = None
    related_entity: RelatedEntity | None = None
    actions: list[Action] | None = None
    raw_event_id: UUID | None = Field(None, description='對應 domain event，除錯用')


class MessageRole(StrEnum):
    user = 'user'
    assistant = 'assistant'
    system = 'system'


class MessageType(StrEnum):
    text = 'text'
    image = 'image'
    audio = 'audio'
    video = 'video'
    sticker = 'sticker'


class Message(BaseModel):
    id: UUID
    conversation_id: UUID
    role: MessageRole
    type: MessageType
    content: str
    media_url: AnyUrl | None = None
    created_at: AwareDatetime


class MessagePage(CursorPage):
    items: list[Message] | None = None


class DoorStatus(StrEnum):
    locked_out = 'locked_out'
    partially_functional = 'partially_functional'
    normal = 'normal'


class NetworkStatus(StrEnum):
    online = 'online'
    offline = 'offline'
    unknown = 'unknown'


class Intent(StrEnum):
    unlock_request = 'unlock_request'
    repair_request = 'repair_request'
    installation = 'installation'
    inquiry = 'inquiry'


class ProblemCardCreateRequest(BaseModel):
    conversation_id: UUID
    brand: constr(max_length=50)
    model: constr(max_length=100)
    symptom: constr(max_length=1000)
    category: str | None = None
    urgency: Urgency
    location: str | None = None
    door_status: DoorStatus | None = None
    network_status: NetworkStatus | None = None
    symptoms: list[str] | None = None
    intent: Intent | None = None
    media_urls: list[AnyUrl] | None = None


class ProblemCardUpdateRequest(BaseModel):
    brand: str | None = None
    model: str | None = None
    symptom: str | None = None
    category: str | None = None
    urgency: Urgency | None = None
    status: ProblemCardStatus | None = None
    media_urls: list[AnyUrl] | None = None


class ResolutionLayer1(StrEnum):
    L1 = 'L1'
    L2 = 'L2'
    L3 = 'L3'


class ProblemCardResolveRequest(BaseModel):
    resolution_layer: ResolutionLayer1 = Field(
        ..., description='L1=AI 直接回覆、L2=技師遠端指導、L3=現場派工。'
    )


class ConvertProblemCardToWorkOrderRequest(BaseModel):
    customer_address: constr(max_length=500) | None = Field(
        None, description='派工地址（覆寫 user profile）'
    )
    customer_name: constr(max_length=100) | None = Field(
        None, description='客戶姓名（覆寫 user.display_name）'
    )
    customer_phone: constr(max_length=50) | None = Field(
        None, description='客戶電話（覆寫 user.phone）'
    )


class ConversationChannel(StrEnum):
    line = 'line'
    web = 'web'
    voice = 'voice'


class ConversationCreateRequest(BaseModel):
    line_user_id: constr(max_length=255) = Field(
        ..., description='LINE Platform User ID (U + 32 hex chars)'
    )
    session_id: constr(max_length=255) = Field(
        ..., description='業務 unique key（對 line_user_id + 30 min idle window）'
    )
    display_name: constr(max_length=255) | None = Field(
        None, description='LINE 顯示名稱（從 LINE Get Profile API 取得）'
    )
    channel: ConversationChannel = Field(
        ConversationChannel.line, description='進入通道'
    )


class RefundReasonCode(StrEnum):
    defective_product = 'defective_product'
    service_quality = 'service_quality'
    customer_dissatisfaction = 'customer_dissatisfaction'
    billing_error = 'billing_error'
    other = 'other'


class RefundRequestedByRole(StrEnum):
    customer_via_line = 'customer_via_line'
    customer_service = 'customer_service'
    manager = 'manager'


class RefundRequestCreateRequest(BaseModel):
    work_order_id: UUID
    amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$') = Field(..., description='退款金額')
    reason: constr(max_length=500) = Field(..., description='退款原因敘述')
    reason_code: RefundReasonCode = Field(
        ..., description='退款原因分類（業務 key 一部分）'
    )
    requires_dual_sign: bool | None = Field(
        None, description='強制雙簽（若 None 由後端依金額閾值判斷）'
    )
    requested_by_role: RefundRequestedByRole = Field(
        ..., description='觸發路徑（dual-trigger 區分）'
    )


class WarrantyClaimType(StrEnum):
    defective = 'defective'
    malfunction = 'malfunction'
    premature_failure = 'premature_failure'
    missing_parts = 'missing_parts'
    other = 'other'


class WarrantyRequestedByRole(StrEnum):
    customer_via_line = 'customer_via_line'
    customer_service = 'customer_service'
    technician = 'technician'


class WarrantyClaimCreateRequest(BaseModel):
    work_order_id: UUID | None = None
    customer_id: UUID
    device_brand: constr(max_length=100)
    device_model: constr(max_length=100)
    claim_type: WarrantyClaimType
    purchase_date: date | None = None
    dispute_reason: constr(max_length=500) | None = None
    requested_by_role: WarrantyRequestedByRole


class SopDraftSourceType(StrEnum):
    case_entry = 'case_entry'
    problem_card = 'problem_card'
    conversation = 'conversation'


class SopDraftCreateRequest(BaseModel):
    source_case_id: UUID = Field(
        ..., description='來源 case_entry / problem_card / conversation ID'
    )
    source_type: SopDraftSourceType = Field(
        SopDraftSourceType.problem_card, description='來源類型'
    )
    draft_content: str = Field(..., description='LLM extracted SOP markdown content')
    model_version: constr(max_length=50) = Field(
        ..., description='產生此 draft 的 LLM 模型 + 版本（idempotency key 一部分）'
    )
    confidence_score: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='LLM extract confidence'
    )


class ProblemCardEnvelope(ApiResponseGeneric):
    data: ProblemCard | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class Format(StrEnum):
    pdf = 'pdf'
    json = 'json'
    csv = 'csv'


class ProblemCardExport(BaseModel):
    format: Format
    content: str = Field(..., description='Base64 編碼內容或下載 URL（依 format 決定）')
    download_url: AnyUrl | None = None


class CaseEntryEmbeddingStatus(StrEnum):
    processing = 'processing'
    ready = 'ready'
    failed = 'failed'


class CaseEntry(BaseModel):
    id: UUID
    title: constr(max_length=200)
    problem_description: constr(max_length=2000)
    solution: constr(max_length=5000)
    brand: constr(max_length=50)
    model: constr(max_length=100) | None = None
    tags: list[str] | None = None
    verified: bool
    embedding_status: CaseEntryEmbeddingStatus
    created_at: AwareDatetime
    updated_at: AwareDatetime


class CaseEntryCreateRequest(BaseModel):
    title: constr(max_length=200)
    problem_description: constr(max_length=2000)
    solution: constr(max_length=5000)
    brand: constr(max_length=50)
    model: constr(max_length=100) | None = None
    tags: list[str] | None = None


class CaseEntryUpdateRequest(BaseModel):
    title: str | None = None
    problem_description: str | None = None
    solution: str | None = None
    brand: str | None = None
    model: str | None = None
    tags: list[str] | None = None
    verified: bool | None = None


class CaseEntryEnvelope(ApiResponseGeneric):
    data: CaseEntry | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class CaseEntryPage(CursorPage):
    items: list[CaseEntry] | None = None


class CaseSearchRequest(BaseModel):
    query: constr(max_length=500)
    brand: str | None = None
    model: str | None = None
    limit: conint(ge=1, le=20) | None = 5
    similarity_threshold: confloat(ge=0.0, le=1.0) | None = 0.75


class CaseSearchHit(BaseModel):
    case: CaseEntry
    score: confloat(ge=0.0, le=1.0)


class CaseSearchResponse(BaseModel):
    hits: list[CaseSearchHit]


class ManualStatus(StrEnum):
    processing = 'processing'
    ready = 'ready'
    failed = 'failed'


class Manual(BaseModel):
    id: UUID
    title: constr(max_length=200)
    brand: str
    model: str | None = None
    file_name: str
    file_size_bytes: conint(ge=0)
    status: ManualStatus
    chunk_count: conint(ge=0) | None = None
    created_at: AwareDatetime


class ManualEnvelope(ApiResponseGeneric):
    data: Manual | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class ManualPage(CursorPage):
    items: list[Manual] | None = None


class SopDraftStatus(StrEnum):
    draft = 'draft'
    under_review = 'under_review'
    approved = 'approved'
    rejected = 'rejected'


class SopDraftStep(BaseModel):
    order: conint(ge=1)
    title: constr(max_length=200)
    description: constr(max_length=2000)


class SopDraft(BaseModel):
    id: UUID
    document_number: constr(max_length=30) | None = Field(
        None, description='SopDraft 編號 SOP-YYYYMMDD-NNNN（ERP 引用號）'
    )
    case_event_id: UUID | None = None
    problem_card_id: UUID | None = None
    title: constr(max_length=200)
    steps: list[SopDraftStep]
    status: SopDraftStatus
    reviewer_id: UUID | None = None
    reviewed_at: AwareDatetime | None = None
    review_comment: str | None = None
    created_at: AwareDatetime


class SopDraftEnvelope(ApiResponseGeneric):
    data: SopDraft | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class SopDraftPage(CursorPage):
    items: list[SopDraft] | None = None


class Decision2(StrEnum):
    approve = 'approve'
    reject = 'reject'


class SopDraftReviewRequest(BaseModel):
    decision: Decision2
    comment: constr(max_length=1000) | None = None


class SopDraftAdoptRequest(BaseModel):
    target_case_id: UUID | None = Field(
        None, description='採納為現有案例的更新；省略則建立新案例'
    )


class ResolveRequest(BaseModel):
    problem_card_id: UUID


class Layer(StrEnum):
    faq_match = 'faq_match'
    knowledge_base_rag = 'knowledge_base_rag'
    llm_generation = 'llm_generation'
    escalation = 'escalation'


class Type1(StrEnum):
    case = 'case'
    manual = 'manual'


class Source1(BaseModel):
    type: Type1 | None = None
    id: UUID | None = None
    snippet: str | None = None
    score: float | None = None


class ResolveResponse(BaseModel):
    layer: Layer
    answer: str
    sources: list[Source1] | None = None
    confidence: confloat(ge=0.0, le=1.0) | None = None


class AuthRefreshRequest(BaseModel):
    refresh_token: str


class AuthLogoutRequest(BaseModel):
    refresh_token: str | None = None


class ChangePasswordRequest(BaseModel):
    current_password: constr(min_length=8, max_length=72)
    new_password: constr(min_length=8, max_length=72)


class DashboardPeriod(StrEnum):
    today = 'today'
    field_7d = '7d'
    field_30d = '30d'
    field_90d = '90d'


class Conversations(BaseModel):
    total: conint(ge=0)
    active: conint(ge=0)
    resolved: conint(ge=0)
    escalated: conint(ge=0)


class Resolution(BaseModel):
    ai_resolution_rate: confloat(ge=0.0, le=1.0) | None = None
    avg_resolution_time_seconds: conint(ge=0) | None = None
    by_layer: dict[str, int] | None = None


class HotTopic(BaseModel):
    topic: str | None = None
    count: conint(ge=0) | None = None


class TokenUsage(BaseModel):
    total_tokens: int | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    estimated_cost_usd: float | None = None


class TopBrand(BaseModel):
    brand: str | None = None
    count: conint(ge=0) | None = None


class WorkOrders(BaseModel):
    today_count: conint(ge=0) | None = Field(None, description='今日新建工單數')
    completion_rate: confloat(ge=0.0, le=1.0) | None = Field(
        None,
        description='今日完工率 = 今日完工 / 今日新建（today_count == 0 時為 null）',
    )
    overdue_count: conint(ge=0) | None = Field(
        None,
        description='排程時間已過且未結案（status NOT IN completed/closed/cancelled）',
    )


class Technicians(BaseModel):
    total_count: conint(ge=0) | None = Field(
        None, description="此租戶啟用中（status='active'）的技師總數"
    )
    online_count: conint(ge=0) | None = Field(
        None, description='目前可派遣的技師數（active 且不在執行中工單）'
    )
    dispatchable_count: conint(ge=0) | None = Field(
        None, description='已上線且可立即指派（保留欄位，目前等同 online_count）'
    )


class DashboardStats(BaseModel):
    period: DashboardPeriod
    conversations: Conversations
    resolution: Resolution
    hot_topics: list[HotTopic] | None = None
    token_usage: TokenUsage | None = None
    top_brands: list[TopBrand] | None = None
    work_orders: WorkOrders | None = Field(
        None,
        description='派工今日 KPI（today_count / completion_rate / overdue_count）。',
    )
    technicians: Technicians | None = Field(
        None,
        description='技師概況 KPI（total_count / online_count / dispatchable_count）。',
    )


class RevenueKpis(BaseModel):
    month_revenue: constr(pattern=r'^-?\d+(\.\d{1,2})?$') = Field(
        ..., description='本月營收（已開立 invoice issued + paid 加總，TWD 字串）'
    )
    average_invoice_amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$') = Field(
        ..., description='平均 invoice 金額'
    )
    paid_rate: confloat(ge=0.0, le=1.0) = Field(
        ...,
        description='付款成功率 = paid / (issued + paid + cancelled)；無發票時為 null',
    )
    outstanding_amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$') = Field(
        ..., description="未收帳款金額（DB status='draft' 加總）"
    )
    outstanding_count: conint(ge=0) = Field(..., description='未收帳款筆數')


class RevenueTrendPoint(BaseModel):
    period: str = Field(..., description='期間標籤（例 2026-04）')
    revenue: constr(pattern=r'^-?\d+(\.\d{1,2})?$') = Field(
        ..., description='期間內已開立 invoice 金額（TWD 字串）'
    )
    order_count: conint(ge=0) = Field(..., description='期間內 invoice 筆數')


class RevenueByBrandPoint(BaseModel):
    brand: str
    revenue: constr(pattern=r'^-?\d+(\.\d{1,2})?$')
    share: confloat(ge=0.0, le=1.0) = Field(..., description='占總營收比例')


class Granularity(StrEnum):
    day = 'day'
    week = 'week'
    month = 'month'


class RevenueSummary(BaseModel):
    granularity: Granularity
    kpis: RevenueKpis
    trend: list[RevenueTrendPoint]
    by_brand: list[RevenueByBrandPoint]


class KpiFunnel(BaseModel):
    conversations: conint(ge=0)
    problem_cards: conint(ge=0)
    work_orders: conint(ge=0)
    dispatched: conint(ge=0)
    completed: conint(ge=0)


class KpiDisputeRates(BaseModel):
    refund_rate: constr(pattern=r'^-?\d+(\.\d{1,4})?$') | None = Field(
        None, description='退款率（refund_requests 數 / work_orders 總數）'
    )
    warranty_claim_rate: constr(pattern=r'^-?\d+(\.\d{1,4})?$') | None = Field(
        None, description='保固索賠率（warranty_claims 數 / work_orders 總數）'
    )
    dispute_rate: constr(pattern=r'^-?\d+(\.\d{1,4})?$') | None = Field(
        None, description='爭議升級率（disputes 數 / work_orders 總數）'
    )


class KpiTechnicianEfficiency(BaseModel):
    avg_handle_minutes: confloat(ge=0.0) | None = Field(
        None, description='平均處理時長（分鐘）；無樣本時 null'
    )
    completed_count: conint(ge=0) | None = None


class KpiReport(BaseModel):
    period: DashboardPeriod
    generated_at: AwareDatetime
    funnel: KpiFunnel
    dispute_rates: KpiDisputeRates
    technician_efficiency: KpiTechnicianEfficiency
    notes: list[str] | None = Field(
        None, description='暫不可計算的指標（SLA / NPS / 滿意度 / FTFR / 差評率）說明'
    )


class Rag(BaseModel):
    similarity_threshold: confloat(ge=0.0, le=1.0) | None = None
    max_results: conint(ge=1) | None = None
    chunk_size: conint(ge=1) | None = None
    chunk_overlap: conint(ge=0) | None = None


class Llm(BaseModel):
    model: str | None = None
    temperature: confloat(ge=0.0, le=2.0) | None = None
    max_tokens: conint(ge=1) | None = None
    system_prompt_version: str | None = None


class Resolution1(BaseModel):
    faq_confidence_threshold: confloat(ge=0.0, le=1.0) | None = None
    rag_confidence_threshold: confloat(ge=0.0, le=1.0) | None = None
    auto_escalation_enabled: bool | None = None


class LineBot(BaseModel):
    greeting_message_enabled: bool | None = None
    max_conversation_turns: conint(ge=1) | None = None


class SystemConfig(BaseModel):
    rag: Rag | None = None
    llm: Llm | None = None
    resolution: Resolution1 | None = None
    line_bot: LineBot | None = None


class AuditLogType(StrEnum):
    api_call = 'api_call'
    llm_interaction = 'llm_interaction'
    rag_retrieval = 'rag_retrieval'
    admin_action = 'admin_action'
    agent_message = 'agent_message'


class AuditLogEntry(BaseModel):
    id: UUID
    log_type: AuditLogType
    actor_id: UUID | None = None
    action: constr(max_length=200)
    details: dict[str, Any] | None = None
    created_at: AwareDatetime


class AuditLogPage(CursorPage):
    items: list[AuditLogEntry] | None = None


class SentimentAlertStatus(StrEnum):
    pending = 'pending'
    acknowledged = 'acknowledged'
    resolved = 'resolved'


class SentimentLabel(StrEnum):
    negative = 'negative'
    very_negative = 'very_negative'
    neutral = 'neutral'
    positive = 'positive'


class SentimentAlert(BaseModel):
    id: UUID
    conversation_id: UUID
    consumer_message: constr(max_length=2000) | None = None
    sentiment_label: SentimentLabel
    confidence: confloat(ge=0.0, le=1.0)
    detected_keywords: list[str] | None = None
    problem_card_id: UUID | None = None
    status: SentimentAlertStatus
    notified_admin_ids: list[UUID] | None = None
    admin_note: constr(max_length=1000) | None = None
    created_at: AwareDatetime


class SentimentAlertUpdateRequest(BaseModel):
    status: SentimentAlertStatus
    admin_note: constr(max_length=1000) | None = None


class SentimentAlertPage(CursorPage):
    items: list[SentimentAlert] | None = None


class FamilyReviewAction(StrEnum):
    approved = 'approved'
    rejected = 'rejected'


class FamilyReviewPendingItem(BaseModel):
    sop_draft_id: UUID
    title: str
    admin_reviewer: str | None = None
    admin_approved_at: AwareDatetime | None = None
    awaiting_family_review_since: AwareDatetime


class FamilyReviewPendingResponse(BaseModel):
    data: list[FamilyReviewPendingItem]


class FamilyReviewCreateRequest(BaseModel):
    sop_draft_id: UUID
    action: FamilyReviewAction
    comment: constr(max_length=1000) | None = None


class FamilyReview(BaseModel):
    id: UUID
    sop_draft_id: UUID
    action: FamilyReviewAction
    reviewer_id: UUID
    comment: str | None = None
    created_at: AwareDatetime


class FamilyReviewPage(CursorPage):
    items: list[FamilyReview] | None = None


class KbExportStatus(StrEnum):
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'


class Scope(StrEnum):
    all = 'all'
    cases_only = 'cases_only'
    manuals_only = 'manuals_only'


class KbExportRequest(BaseModel):
    scope: Scope | None = 'all'
    brand: str | None = None


class KbExportJob(BaseModel):
    job_id: UUID
    status: KbExportStatus
    download_url: AnyUrl | None = None
    item_count: conint(ge=0) | None = None
    created_at: AwareDatetime
    completed_at: AwareDatetime | None = None


class TechnicianRegisterRequest(BaseModel):
    name: str
    phone: constr(pattern=r'^09\d{8}$')
    email: EmailStr
    password: SecretStr
    capabilities: list[str]
    regions: list[str]


class TechnicianProfile(Technician):
    email: EmailStr | None = None


class TechnicianProfileEnvelope(ApiResponseGeneric):
    data: TechnicianProfile | None = Field(
        None, description='實際載荷，由各 endpoint 具體化'
    )


class TechnicianUpdateRequest(BaseModel):
    name: str | None = None
    phone: constr(pattern=r'^09\d{8}$') | None = None
    email: EmailStr | None = None
    capabilities: list[str] | None = None
    regions: list[str] | None = None


class MyAvailabilityState(StrEnum):
    available = 'available'
    busy = 'busy'
    offline = 'offline'
    on_leave = 'on_leave'
    circuit_breaker_open = 'circuit_breaker_open'


class MyAvailabilityUpdateRequest(BaseModel):
    online_state: MyAvailabilityState


class MyAvailabilityData(BaseModel):
    id: UUID
    name: str
    online_state: MyAvailabilityState


class MyAvailabilityResponse(ApiResponseGeneric):
    data: MyAvailabilityData | None = Field(
        None, description='更新後的技師在線狀態'
    )


class WorkOrderConfirmRequest(BaseModel):
    rating: conint(ge=1, le=5)
    feedback: constr(max_length=1000) | None = None


class Urgency1(StrEnum):
    normal = 'normal'
    emergency = 'emergency'


class DispatchAutoMatchRequest(BaseModel):
    problem_card_id: UUID
    urgency: Urgency1 | None = 'normal'
    max_candidates: conint(ge=1, le=10) | None = 3


class DispatchCandidate(BaseModel):
    technician_id: UUID
    technician_name: str | None = None
    score: confloat(ge=0.0, le=1.0)
    distance_km: float | None = None
    eta_minutes: conint(ge=0) | None = None
    rating: confloat(ge=0.0, le=5.0) | None = None


class DispatchAutoMatchResponse(BaseModel):
    candidates: list[DispatchCandidate]


class DispatchAssignRequest(BaseModel):
    work_order_id: UUID
    technician_id: UUID
    override_reason: constr(max_length=500) | None = None


class LockType(StrEnum):
    digital_deadbolt = 'digital_deadbolt'
    smart_lock = 'smart_lock'
    padlock = 'padlock'
    other = 'other'


class DifficultyLevel(StrEnum):
    simple = 'simple'
    moderate = 'moderate'
    complex = 'complex'


class PricingCalculateRequest(BaseModel):
    brand: str
    model: str | None = None
    lock_type: LockType
    difficulty: DifficultyLevel
    is_emergency: bool | None = False
    is_night_service: bool | None = False
    additional_items: list[str] | None = None


class PricingSurcharge(BaseModel):
    name: str
    condition: str | None = None
    amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$')


class PricingCalculateResponse(BaseModel):
    base_price: constr(pattern=r'^-?\d+(\.\d{1,2})?$')
    surcharges: list[PricingSurcharge] | None = None
    total: constr(pattern=r'^-?\d+(\.\d{1,2})?$')
    currency: Currency | None = 'TWD'


class PricingRule(BaseModel):
    id: UUID
    brand: str
    lock_type: LockType
    difficulty: DifficultyLevel
    base_price: constr(pattern=r'^-?\d+(\.\d{1,2})?$')
    surcharges: list[PricingSurcharge] | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class PricingRuleCreateRequest(BaseModel):
    brand: str
    lock_type: LockType
    difficulty: DifficultyLevel
    base_price: constr(pattern=r'^-?\d+(\.\d{1,2})?$')
    surcharges: list[PricingSurcharge] | None = None


class PricingRuleUpdateRequest(BaseModel):
    base_price: constr(pattern=r'^-?\d+(\.\d{1,2})?$') | None = None
    surcharges: list[PricingSurcharge] | None = None


class PricingRuleEnvelope(ApiResponseGeneric):
    data: PricingRule | None = Field(None, description='實際載荷，由各 endpoint 具體化')


class PricingRulePage(CursorPage):
    items: list[PricingRule] | None = None


class ReconciliationStatus(StrEnum):
    pending = 'pending'
    approved = 'approved'
    disputed = 'disputed'


class Reconciliation(BaseModel):
    id: UUID
    technician_id: UUID
    technician_name: str | None = None
    period_start: AwareDatetime
    period_end: AwareDatetime
    total_orders: conint(ge=0)
    total_revenue: constr(pattern=r'^-?\d+(\.\d{1,2})?$')
    platform_fee: constr(pattern=r'^-?\d+(\.\d{1,2})?$') | None = None
    technician_payout: constr(pattern=r'^-?\d+(\.\d{1,2})?$')
    status: ReconciliationStatus
    approved_by: UUID | None = None
    approved_at: AwareDatetime | None = None
    created_at: AwareDatetime


class ReconciliationApproveRequest(BaseModel):
    note: constr(max_length=500) | None = None


class ReconciliationPage(CursorPage):
    items: list[Reconciliation] | None = None


class SettlementStatus(StrEnum):
    pending = 'pending'
    paid = 'paid'
    failed = 'failed'


class PaymentMethod(StrEnum):
    bank_transfer = 'bank_transfer'
    other = 'other'


class Settlement(BaseModel):
    id: UUID
    reconciliation_id: UUID
    technician_id: UUID
    technician_name: str | None = None
    amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$')
    currency: Currency
    status: SettlementStatus
    payment_method: PaymentMethod | None = None
    paid_at: AwareDatetime | None = None
    created_at: AwareDatetime


class SettlementPage(CursorPage):
    items: list[Settlement] | None = None


class RelatedEntityType(StrEnum):
    reconciliation = 'reconciliation'
    settlement = 'settlement'
    refund = 'refund'
    invoice = 'invoice'


class Voucher(BaseModel):
    id: UUID
    voucher_number: str
    related_entity_type: RelatedEntityType | None = None
    related_entity_id: UUID | None = None
    debit_account: str
    credit_account: str
    amount: constr(pattern=r'^-?\d+(\.\d{1,2})?$')
    currency: Currency
    posting_date: date
    memo: str | None = None
    created_at: AwareDatetime


class VoucherPage(CursorPage):
    items: list[Voucher] | None = None


class TargetType(StrEnum):
    technician = 'technician'
    admin = 'admin'
    customer = 'customer'


class Channel(StrEnum):
    push = 'push'
    sms = 'sms'
    line = 'line'
    email = 'email'


class NotificationPushRequest(BaseModel):
    target_type: TargetType
    target_id: UUID
    type: NotificationType
    title: constr(max_length=200)
    body: constr(max_length=1000)
    data: dict[str, Any] | None = None
    channels: list[Channel] | None = None


class ApiErrorResponse(BaseModel):
    error_code: str = Field(
        ...,
        description='統一錯誤碼（見 `docs/02-design/error-codes.md`）',
        examples=[
            'VALIDATION_ERROR',
            'UNAUTHORIZED',
            'FORBIDDEN',
            'NOT_FOUND',
            'CONFLICT',
            'OPTIMISTIC_LOCK_FAILED',
            'RATE_LIMITED',
            'IDEMPOTENCY_KEY_REUSED',
            'TENANT_MISMATCH',
            'INTERNAL_ERROR',
            'SERVICE_UNAVAILABLE',
            'WORK_ORDER_CONFLICT',
            'WORK_ORDER_STATUS_INVALID',
            'QUOTE_EXPIRED',
            'TECHNICIAN_CIRCUIT_BREAKER_OPEN',
            'TECHNICIAN_SCHEDULE_CONFLICT',
            'DISPATCH_NO_TECHNICIAN_AVAILABLE',
            'DISPATCH_OVERRIDE_REQUIRED',
            'DISPATCH_REASON_MISSING',
            'SIGNATURE_ALREADY_SIGNED',
            'APPEARANCE_CHANGE_SIGNATURE_REJECTED',
            'APPEARANCE_CHANGE_EVIDENCE_INCOMPLETE',
            'REFUND_DUAL_SIGN_REQUIRED',
            'REFUND_DECISION_LOCKED',
            'COMPLAINT_ALREADY_IN_DISPUTE',
            'DISPUTE_MERGE_FAILED',
            'DISPUTE_EXTERNAL_PENDING',
            'DISPUTE_SLA_OVERDUE',
            'INVENTORY_INSUFFICIENT',
            'INVENTORY_PART_NOT_FOUND',
            'ROLE_IN_USE',
            'PERMISSION_CODE_INVALID',
            'AUDIT_EXPORT_TOO_LARGE',
            'DIAGNOSTIC_STREAM_CLOSED',
            'TENANT_SUSPENDED',
            'TENANT_LINE_BINDING_FAILED',
            'TENANT_NOT_FOUND',
            'BRAND_CONFIG_INVALID',
            'BRAND_REVIEW_PENDING',
            'TENANT_QUOTA_EXCEEDED',
            'NOTIFICATION_NOT_FOUND',
            'NOTIFICATION_BULK_LIMIT_EXCEEDED',
            'RESCHEDULE_LIMIT_EXCEEDED',
            'RESCHEDULE_RSVP_EXPIRED',
            'RESCHEDULE_SLOT_TAKEN',
        ],
    )
    message: str = Field(..., description='使用者可見訊息（依 Accept-Language i18n）')
    details: list[ApiFieldError] | None = None
