# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from datetime import date
from enum import Enum, StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field, SecretStr


class ApiResponseGeneric(BaseModel):
    data: Any
    """
    實際載荷，由各 endpoint 具體化
    """
    message: str | None = None


class ApiFieldError(BaseModel):
    field: str
    message: str


class CursorPage(BaseModel):
    items: list[Any]
    next_cursor: str | None = None
    has_more: bool
    total_count: int | None = None


class LoginRequest(BaseModel):
    email: EmailStr
    password: SecretStr = Field(..., min_length=8)


class TokenType(StrEnum):
    Bearer = 'Bearer'


class Data(BaseModel):
    """
    實際載荷，由各 endpoint 具體化
    """

    access_token: str
    refresh_token: str
    """
    用於 /auth/refresh 換發 access token
    """
    token_type: TokenType
    expires_in: int
    """
    access_token 有效秒數
    """


class LoginResponse(ApiResponseGeneric):
    data: Data | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class ConversationStatus(StrEnum):
    active = 'active'
    waiting_human = 'waiting_human'
    closed = 'closed'


class ResolutionLayer(Enum):
    case_library = 'case_library'
    rag = 'rag'
    human = 'human'
    NoneType_None = None


class Conversation(BaseModel):
    id: UUID
    line_user_id: str
    display_name: str
    status: ConversationStatus
    resolution_layer: ResolutionLayer | None = None
    message_count: int = Field(..., ge=0)
    created_at: AwareDatetime
    updated_at: AwareDatetime


class ConversationEnvelope(ApiResponseGeneric):
    data: Conversation | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class ConversationPage(CursorPage):
    items: list[Conversation] | None = None


class ProblemCardStatus(StrEnum):
    draft = 'draft'
    confirmed = 'confirmed'
    resolved = 'resolved'


class Urgency(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class ProblemCard(BaseModel):
    id: UUID
    conversation_id: UUID
    brand: str = Field(..., max_length=50)
    model: str = Field(..., max_length=100)
    symptom: str = Field(..., max_length=1000)
    category: str
    urgency: Urgency
    confidence_score: float | None = Field(None, ge=0.0, le=1.0)
    """
    AI 分類信心分數（閾值 0.6 以下觸發人工覆核）
    """
    status: ProblemCardStatus
    media_urls: list[AnyUrl] | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class ProblemCardPage(CursorPage):
    items: list[ProblemCard] | None = None


class WorkOrderStatus(StrEnum):
    """
    16 狀態工單狀態機（見 `E5x--work-order-interaction-flows.md §18.3`）

    """

    inquiring = 'inquiring'
    qualified = 'qualified'
    quoted = 'quoted'
    negotiating = 'negotiating'
    accepted = 'accepted'
    scheduled = 'scheduled'
    dispatching = 'dispatching'
    assigned = 'assigned'
    en_route = 'en_route'
    arrived = 'arrived'
    in_progress = 'in_progress'
    completed = 'completed'
    billed = 'billed'
    paid = 'paid'
    closed = 'closed'
    cancelled = 'cancelled'


class WorkOrder(BaseModel):
    id: UUID
    problem_card_id: UUID
    technician_id: UUID | None = None
    status: WorkOrderStatus
    district: str
    address: str
    brand: str
    model: str
    urgency: Urgency
    estimated_reward: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,2})?$')
    """
    Decimal(10,2) 序列化為字串以避免 JS 浮點誤差
    """
    scheduled_time: AwareDatetime | None = None
    actual_arrival: AwareDatetime | None = None
    completion_time: AwareDatetime | None = None
    version: int | None = None
    """
    樂觀鎖版本號，更新時 server 比對
    """
    created_at: AwareDatetime
    updated_at: AwareDatetime


class WorkOrderEnvelope(ApiResponseGeneric):
    data: WorkOrder | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class WorkOrderPage(CursorPage):
    items: list[WorkOrder] | None = None


class PartsUsedItem(BaseModel):
    part_id: UUID
    quantity: int = Field(..., ge=1)


class CompletionReport(BaseModel):
    """
    完工回報。`photos_before` / `photos_after` 暫時為 optional（`minItems: 0`），
    待媒體上傳模組接入後再上修為必填。

    """

    summary: str = Field(..., max_length=2000)
    photos_before: list[AnyUrl] | None = None
    photos_after: list[AnyUrl] | None = None
    parts_used: list[PartsUsedItem] | None = None
    actual_amount: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,2})?$')


class WorkOrderCancelRequest(BaseModel):
    """
    工單取消理由（管理員或上層流程觸發）。
    """

    reason: str | None = Field(None, max_length=500)


class ReasonCode(StrEnum):
    auto_dispatch_exhausted = 'auto_dispatch_exhausted'
    customer_requested_specific_tech = 'customer_requested_specific_tech'
    skill_shortage_override = 'skill_shortage_override'
    sla_rescue = 'sla_rescue'
    other = 'other'


class OverrideFlags(BaseModel):
    allow_circuit: bool | None = False
    allow_cross_area: bool | None = False


class WorkOrderAssignRequest(BaseModel):
    """
    手動指派技師（admin override）。technician_id + reason_code 必填；override_flags 預留 circuit-breaker / cross-area，MVP 一律 false。
    """

    technician_id: UUID
    reason_code: ReasonCode
    reason_text: str | None = Field(None, max_length=500)
    override_flags: OverrideFlags | None = None


class WarrantyClaimStatus(StrEnum):
    filed = 'filed'
    approved = 'approved'
    rejected = 'rejected'
    in_progress = 'in_progress'
    closed = 'closed'


class WarrantyClaim(BaseModel):
    """
    保固申請（read-only）
    """

    id: UUID
    work_order_id: UUID | None = None
    customer_id: UUID
    device_brand: str
    device_model: str
    purchase_date: date | None = None
    warranty_start_date: date
    """
    保固起始日（以「交屋日期」為準）
    """
    warranty_end_date: date
    claim_date: date
    is_within_warranty: bool
    status: WarrantyClaimStatus
    dispute_reason: str | None = None
    verification_source: str | None = None
    resolution: str | None = None
    discount_offered: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,2})?$')
    """
    折讓金額（無保固但提供折讓時）
    """
    created_at: AwareDatetime
    updated_at: AwareDatetime


class WarrantyClaimEnvelope(ApiResponseGeneric):
    data: WarrantyClaim | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class WarrantyClaimPage(CursorPage):
    items: list[WarrantyClaim] | None = None


class RefundRequestStatus(StrEnum):
    pending = 'pending'
    approved = 'approved'
    rejected = 'rejected'
    escalated = 'escalated'
    executed = 'executed'
    cancelled = 'cancelled'


class RefundRequest(BaseModel):
    """
    退款申請（read-only；雙簽流程經 submitRefundDecision 推進）
    """

    id: UUID
    work_order_id: UUID
    invoice_id: UUID | None = None
    complaint_id: UUID | None = None
    requested_by: UUID
    amount: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    reason: str
    status: RefundRequestStatus
    requires_dual_sign: bool | None = None
    approval_chain: list[dict[str, Any]] | None = None
    """
    審批鏈（已記錄的決策步驟，順序由舊到新）
    """
    executed_at: AwareDatetime | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class RefundRequestEnvelope(ApiResponseGeneric):
    data: RefundRequest | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class RefundRequestPage(CursorPage):
    items: list[RefundRequest] | None = None


class DisputeType(StrEnum):
    """
    爭議類型（pricing 價格 / quality 品質 / warranty 保固 / cancellation_fee 取消費 / settlement 結算）
    """

    pricing = 'pricing'
    quality = 'quality'
    warranty = 'warranty'
    cancellation_fee = 'cancellation_fee'
    settlement = 'settlement'


class DisputeStatus(StrEnum):
    """
    爭議狀態（filed 待處理 / in_review 調解中 / resolved 已結案 / rejected 已駁回 / closed 已關閉）
    """

    filed = 'filed'
    in_review = 'in_review'
    resolved = 'resolved'
    rejected = 'rejected'
    closed = 'closed'


class Dispute(BaseModel):
    """
    爭議案件（read-only；調解動作待 submitDisputeResolution 上線後接入）
    """

    id: UUID
    work_order_id: UUID | None = None
    invoice_id: UUID | None = None
    filed_by: UUID
    dispute_type: DisputeType
    status: DisputeStatus
    description: str
    evidence: dict[str, Any] | list[dict[str, Any]] | None = None
    """
    雙方證據（jsonb；通常為 customer/technician 兩段結構）
    """
    resolution: str | None = None
    resolution_amount: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,2})?$')
    """
    調解金額（部分退款 / 全額退款時填寫）
    """
    resolved_by: UUID | None = None
    filed_at: AwareDatetime
    resolved_at: AwareDatetime | None = None
    sla_deadline: AwareDatetime | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class DisputeEnvelope(ApiResponseGeneric):
    data: Dispute | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class DisputePage(CursorPage):
    items: list[Dispute] | None = None


class Decision(StrEnum):
    approve = 'approve'
    reject = 'reject'
    escalate = 'escalate'


class RefundDecision(BaseModel):
    decision: Decision
    reason: str = Field(..., max_length=500)
    dual_sign_required: bool | None = None
    """
    金額門檻以上需第二簽核者
    """


class RefundEnvelope(ApiResponseGeneric):
    pass


class SignaturePayload(BaseModel):
    customer_signature: str
    """
    Base64 編碼的簽章影像或 SVG Path
    """
    technician_signature: str
    gps_lat: float | None = None
    gps_lng: float | None = None
    signed_at: AwareDatetime | None = None


class DispatchAction(StrEnum):
    """
    派工事件類型（assign 指派 / accept 接受 / reject 拒絕 / timeout 超時 / reassign 重派 / cancel 取消）
    """

    assign = 'assign'
    accept = 'accept'
    reject = 'reject'
    timeout = 'timeout'
    reassign = 'reassign'
    cancel = 'cancel'


class DispatchLog(BaseModel):
    """
    派工歷程紀錄（read-only；單一工單可有多筆代表派工嘗試序列）
    """

    id: UUID
    work_order_id: UUID
    action: DispatchAction
    technician_id: UUID | None = None
    technician_name: str | None = None
    """
    由 technicians 表 JOIN 取得方便前端顯示
    """
    match_score: float | None = None
    """
    AI 媒合分數（0-100）
    """
    match_factors: dict[str, Any] | None = None
    """
    媒合因子（jsonb；通常為 distance/skill/availability 加權結構）
    """
    rejection_reason: str | None = None
    timeout_seconds: int | None = None
    notes: str | None = None
    created_at: AwareDatetime


class DispatchLogPage(CursorPage):
    items: list[DispatchLog] | None = None


class DispatchQueueSnapshot(BaseModel):
    pending: int
    assigning: int
    assigned: int
    sla_at_risk: int | None = None
    """
    2 小時內可能逾期的工單數
    """


class QuoteStatus(StrEnum):
    draft = 'draft'
    sent = 'sent'
    negotiating = 'negotiating'
    accepted = 'accepted'
    rejected = 'rejected'
    expired = 'expired'


class Currency(StrEnum):
    TWD = 'TWD'


class ItemType(StrEnum):
    labor = 'labor'
    parts = 'parts'
    travel = 'travel'
    holiday_surcharge = 'holiday_surcharge'
    appearance_change = 'appearance_change'
    other = 'other'


class BreakdownItem(BaseModel):
    item_type: ItemType
    description: str = Field(..., max_length=200)
    amount: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')


class ProposedBy(StrEnum):
    system = 'system'
    customer = 'customer'
    technician = 'technician'
    admin = 'admin'


class Outcome(StrEnum):
    pending = 'pending'
    accepted = 'accepted'
    rejected = 'rejected'
    counter_offered = 'counter_offered'


class NegotiationHistoryItem(BaseModel):
    round: int | None = Field(None, ge=1)
    proposed_by: ProposedBy | None = None
    proposed_amount: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,2})?$')
    proposed_at: AwareDatetime | None = None
    outcome: Outcome | None = None


class Quote(BaseModel):
    """
    工單報價（對齊 E5x--work-order-interaction-flows.md §17）。
    採區間制：min/max 為當前報價區間，客戶 accept 後 scalar 欄位為最終金額。

    """

    id: UUID
    work_order_id: UUID
    status: QuoteStatus
    min_amount: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    """
    Decimal(10,2) 字串，對應區間下限
    """
    max_amount: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    currency: Currency
    final_amount: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,2})?$')
    """
    客戶 accept 後的最終金額
    """
    breakdown: list[BreakdownItem] | None = None
    """
    報價明細項
    """
    valid_until: AwareDatetime
    """
    有效期（預設 48h）
    """
    negotiation_history: list[NegotiationHistoryItem] | None = None
    """
    議價輪次記錄
    """
    version: int
    """
    樂觀鎖
    """
    created_at: AwareDatetime
    updated_at: AwareDatetime


class QuoteEnvelope(ApiResponseGeneric):
    data: Quote | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class ExceptionType(StrEnum):
    no_show = 'no_show'
    customer_absent = 'customer_absent'
    scope_change_rejected = 'scope_change_rejected'
    material_shortage = 'material_shortage'
    delay_severe = 'delay_severe'
    appearance_refused = 'appearance_refused'
    payment_failed = 'payment_failed'
    quality_complaint = 'quality_complaint'
    schedule_conflict = 'schedule_conflict'
    other = 'other'


class ExceptionStatus(StrEnum):
    open = 'open'
    investigating = 'investigating'
    resolved = 'resolved'
    escalated = 'escalated'
    closed = 'closed'


class Severity(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class ActorType(StrEnum):
    customer = 'customer'
    technician = 'technician'
    system = 'system'
    admin = 'admin'


class Actor(BaseModel):
    actor_type: ActorType | None = None
    actor_id: str | None = None


class Exception(BaseModel):
    """
    工單異常記錄（對齊 E5x--work-order-interaction-flows.md §22 異常返回節點 + 熔斷規則）

    """

    id: UUID
    work_order_id: UUID
    exception_type: ExceptionType
    status: ExceptionStatus
    severity: Severity
    description: str | None = Field(None, max_length=2000)
    return_to_stage: str | None = None
    """
    異常處理後工單應返回的 WorkOrder 狀態
    """
    triggers_circuit_breaker: bool | None = None
    """
    是否觸發技師熔斷計數（24hr 3 次或 12 月 3 次放鴿子）
    """
    actor: Actor | None = None
    resolution: str | None = None
    """
    處理結果描述
    """
    resolved_at: AwareDatetime | None = None
    resolved_by: UUID | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None


class ExceptionEnvelope(ApiResponseGeneric):
    data: Exception | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class ExceptionPage(CursorPage):
    items: list[Exception] | None = None


class InvoiceStatus(StrEnum):
    pending = 'pending'
    issued = 'issued'
    allowance_pending = 'allowance_pending'
    voided = 'voided'
    reopened = 'reopened'


class TaxType(StrEnum):
    taxable = 'taxable'
    zero_rated = 'zero_rated'
    exempt = 'exempt'


class Category(StrEnum):
    """
    稅務分類 — 車馬費獨立開立，不與工單合併
    """

    service_fee = 'service_fee'
    travel_fee = 'travel_fee'
    parts = 'parts'
    other = 'other'


class Invoice(BaseModel):
    """
    電子發票（對齊 E5x--work-order-interaction-flows.md §21 EX5）

    """

    id: UUID
    work_order_id: UUID
    invoice_number: str = Field(..., pattern='^[A-Z]{2}\\d{8}$')
    """
    台灣電子發票號碼（如 AB12345678）
    """
    tax_id: str | None = Field(None, pattern='^\\d{8}$')
    """
    買方統編（選填）
    """
    amount: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    tax_type: TaxType | None = 'taxable'
    status: InvoiceStatus
    issued_at: AwareDatetime
    voided_at: AwareDatetime | None = None
    void_reason: str | None = None
    allowance_amount: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,2})?$')
    """
    折讓金額（退款時部分折讓）
    """
    category: Category | None = None
    """
    稅務分類 — 車馬費獨立開立，不與工單合併
    """
    reopened_from: UUID | None = None
    """
    重開發票的原發票 ID
    """
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None


class InvoiceEnvelope(ApiResponseGeneric):
    data: Invoice | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class InvoicePage(CursorPage):
    items: list[Invoice] | None = None


class TechnicianLevel(StrEnum):
    S = 'S'
    A = 'A'
    B = 'B'
    C = 'C'


class TechnicianAvailability(StrEnum):
    available = 'available'
    busy = 'busy'
    offline = 'offline'
    on_leave = 'on_leave'
    circuit_breaker_open = 'circuit_breaker_open'


class Technician(BaseModel):
    id: UUID
    name: str
    phone: str = Field(..., pattern='^09\\d{8}$')
    level: TechnicianLevel
    availability: TechnicianAvailability
    skills: list[str]
    """
    可服務品牌 / 技能碼清單
    """
    service_areas: list[str]
    """
    服務區域代碼（行政區）
    """
    rating: float = Field(..., ge=0.0, le=5.0)
    completed_orders_count: int | None = Field(None, ge=0)
    circuit_breaker_until: AwareDatetime | None = None
    created_at: AwareDatetime


class TechnicianEnvelope(ApiResponseGeneric):
    data: Technician | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class TechnicianPage(CursorPage):
    items: list[Technician] | None = None


class Customer(BaseModel):
    id: UUID
    display_name: str
    """
    顯示名稱（LINE 名稱或從電話 / userId 推導）
    """
    line_user_id: str | None = None
    """
    LINE Platform User ID（U + 32 hex），可能為空（非 LINE 來源）
    """
    phone: str | None = None
    address: str | None = None
    last_active_at: AwareDatetime | None = None
    """
    最近一次互動時間（users.last_active_at）
    """
    total_conversations: int = Field(..., ge=0)
    total_orders: int = Field(..., ge=0)
    """
    此客戶累積工單數（穿越 conversations → problem_cards → work_orders）
    """
    last_service_at: AwareDatetime | None = None
    """
    最近一次工單完工時間
    """
    created_at: AwareDatetime


class CustomerEnvelope(ApiResponseGeneric):
    data: Customer | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class CustomerPage(CursorPage):
    items: list[Customer] | None = None


class RoleResource(StrEnum):
    """
    系統定義的權限資源類別
    """

    work_orders = 'work_orders'
    technicians = 'technicians'
    customers = 'customers'
    accounting = 'accounting'
    invoices = 'invoices'
    refunds = 'refunds'
    inventory = 'inventory'
    warranty = 'warranty'
    disputes = 'disputes'
    audit_logs = 'audit_logs'
    roles = 'roles'
    system_settings = 'system_settings'


class RolePermission(BaseModel):
    resource: RoleResource
    read: bool
    write: bool
    delete: bool
    locked: bool | None = False
    """
    是否為系統強制鎖定的權限（不可被自訂角色覆寫）
    """


class Role(BaseModel):
    id: str
    """
    角色 ID（system roles 為固定字串：admin / reviewer / technician / brand_oem / line_user）
    """
    name: str
    description: str
    user_count: int = Field(..., ge=0)
    """
    本租戶內擁有此角色的使用者數
    """
    is_system: bool
    """
    是否為系統內建角色（不可刪除）
    """
    permissions: list[RolePermission]


class RolesEnvelope(ApiResponseGeneric):
    data: list[Role] | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class InventoryStockStatus(StrEnum):
    """
    庫存狀態（衍生自 quantity_on_hand 與 reorder_point 比較）
    """

    in_stock = 'in_stock'
    low_stock = 'low_stock'
    out_of_stock = 'out_of_stock'


class InventoryItem(BaseModel):
    id: UUID
    part_number: str
    """
    料號（unique；例：BAT-AA-001）
    """
    name: str
    category: str
    """
    類別（battery / lock_body / circuit_board / screw / side_panel / other）
    """
    brand_compatibility: list[str] | None = None
    """
    適用品牌清單
    """
    unit_cost: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,2})?$')
    """
    單位成本（TWD，decimal 字串；NULL 表示未設定）
    """
    quantity_on_hand: int = Field(..., ge=0)
    reorder_point: int = Field(..., ge=0)
    """
    安全庫存量；quantity_on_hand <= reorder_point 觸發補貨警示
    """
    stock_status: InventoryStockStatus
    supplier: str | None = None
    is_active: bool
    last_restocked_at: AwareDatetime | None = None
    """
    最近一次入庫時間（衍生自 inventory_transactions purchase 紀錄；NULL 表示尚未補貨過）
    """
    created_at: AwareDatetime
    updated_at: AwareDatetime


class InventoryItemPage(CursorPage):
    items: list[InventoryItem] | None = None


class InventoryItemEnvelope(ApiResponseGeneric):
    data: InventoryItem | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class NotificationType(StrEnum):
    work_order = 'work_order'
    refund = 'refund'
    dispute = 'dispute'
    rbac = 'rbac'
    inventory = 'inventory'
    sla = 'sla'
    system = 'system'
    mention = 'mention'


class NotificationSeverity(StrEnum):
    info = 'info'
    warning = 'warning'
    critical = 'critical'


class Source(StrEnum):
    websocket = 'websocket'
    line_push = 'line_push'
    system = 'system'
    email_fallback = 'email_fallback'


class RelatedEntity(BaseModel):
    type: str | None = None
    id: UUID | None = None
    url: AnyUrl | None = None


class Method(StrEnum):
    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'


class Action(BaseModel):
    label: str | None = None
    endpoint: str | None = None
    method: Method | None = None


class Notification(BaseModel):
    id: UUID
    type: NotificationType
    severity: NotificationSeverity
    title: str = Field(..., max_length=200)
    body: str = Field(..., max_length=1000)
    source: Source
    created_at: AwareDatetime
    read_at: AwareDatetime | None = None
    archived_at: AwareDatetime | None = None
    related_entity: RelatedEntity | None = None
    actions: list[Action] | None = None
    raw_event_id: UUID | None = None
    """
    對應 domain event，除錯用
    """


class MessageRole(StrEnum):
    user = 'user'
    assistant = 'assistant'
    system = 'system'


class MessageType(StrEnum):
    text = 'text'
    image = 'image'
    audio = 'audio'
    video = 'video'
    sticker = 'sticker'


class Message(BaseModel):
    id: UUID
    conversation_id: UUID
    role: MessageRole
    type: MessageType
    content: str
    media_url: AnyUrl | None = None
    created_at: AwareDatetime


class MessagePage(CursorPage):
    items: list[Message] | None = None


class DoorStatus(StrEnum):
    locked_out = 'locked_out'
    partially_functional = 'partially_functional'
    normal = 'normal'


class NetworkStatus(StrEnum):
    online = 'online'
    offline = 'offline'
    unknown = 'unknown'


class Intent(StrEnum):
    unlock_request = 'unlock_request'
    repair_request = 'repair_request'
    installation = 'installation'
    inquiry = 'inquiry'


class ProblemCardCreateRequest(BaseModel):
    conversation_id: UUID
    brand: str = Field(..., max_length=50)
    model: str = Field(..., max_length=100)
    symptom: str = Field(..., max_length=1000)
    category: str | None = None
    urgency: Urgency
    location: str | None = None
    door_status: DoorStatus | None = None
    network_status: NetworkStatus | None = None
    symptoms: list[str] | None = None
    intent: Intent | None = None
    media_urls: list[AnyUrl] | None = None


class ProblemCardUpdateRequest(BaseModel):
    brand: str | None = None
    model: str | None = None
    symptom: str | None = None
    category: str | None = None
    urgency: Urgency | None = None
    status: ProblemCardStatus | None = None
    media_urls: list[AnyUrl] | None = None


class ProblemCardEnvelope(ApiResponseGeneric):
    data: ProblemCard | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class Format(StrEnum):
    pdf = 'pdf'
    json = 'json'
    csv = 'csv'


class ProblemCardExport(BaseModel):
    format: Format
    content: str
    """
    Base64 編碼內容或下載 URL（依 format 決定）
    """
    download_url: AnyUrl | None = None


class CaseEntryEmbeddingStatus(StrEnum):
    processing = 'processing'
    ready = 'ready'
    failed = 'failed'


class CaseEntry(BaseModel):
    id: UUID
    title: str = Field(..., max_length=200)
    problem_description: str = Field(..., max_length=2000)
    solution: str = Field(..., max_length=5000)
    brand: str = Field(..., max_length=50)
    model: str | None = Field(None, max_length=100)
    tags: list[str] | None = None
    verified: bool
    embedding_status: CaseEntryEmbeddingStatus
    created_at: AwareDatetime
    updated_at: AwareDatetime


class CaseEntryCreateRequest(BaseModel):
    title: str = Field(..., max_length=200)
    problem_description: str = Field(..., max_length=2000)
    solution: str = Field(..., max_length=5000)
    brand: str = Field(..., max_length=50)
    model: str | None = Field(None, max_length=100)
    tags: list[str] | None = None


class CaseEntryUpdateRequest(BaseModel):
    title: str | None = None
    problem_description: str | None = None
    solution: str | None = None
    brand: str | None = None
    model: str | None = None
    tags: list[str] | None = None
    verified: bool | None = None


class CaseEntryEnvelope(ApiResponseGeneric):
    data: CaseEntry | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class CaseEntryPage(CursorPage):
    items: list[CaseEntry] | None = None


class CaseSearchRequest(BaseModel):
    query: str = Field(..., max_length=500)
    brand: str | None = None
    model: str | None = None
    limit: int | None = Field(5, ge=1, le=20)
    similarity_threshold: float | None = Field(0.75, ge=0.0, le=1.0)


class CaseSearchHit(BaseModel):
    case: CaseEntry
    score: float = Field(..., ge=0.0, le=1.0)


class CaseSearchResponse(BaseModel):
    hits: list[CaseSearchHit]


class ManualStatus(StrEnum):
    processing = 'processing'
    ready = 'ready'
    failed = 'failed'


class Manual(BaseModel):
    id: UUID
    title: str = Field(..., max_length=200)
    brand: str
    model: str | None = None
    file_name: str
    file_size_bytes: int = Field(..., ge=0)
    status: ManualStatus
    chunk_count: int | None = Field(None, ge=0)
    created_at: AwareDatetime


class ManualEnvelope(ApiResponseGeneric):
    data: Manual | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class ManualPage(CursorPage):
    items: list[Manual] | None = None


class SopDraftStatus(StrEnum):
    draft = 'draft'
    under_review = 'under_review'
    approved = 'approved'
    rejected = 'rejected'


class SopDraftStep(BaseModel):
    order: int = Field(..., ge=1)
    title: str = Field(..., max_length=200)
    description: str = Field(..., max_length=2000)


class SopDraft(BaseModel):
    id: UUID
    case_event_id: UUID | None = None
    problem_card_id: UUID | None = None
    title: str = Field(..., max_length=200)
    steps: list[SopDraftStep]
    status: SopDraftStatus
    reviewer_id: UUID | None = None
    reviewed_at: AwareDatetime | None = None
    review_comment: str | None = None
    created_at: AwareDatetime


class SopDraftEnvelope(ApiResponseGeneric):
    data: SopDraft | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class SopDraftPage(CursorPage):
    items: list[SopDraft] | None = None


class Decision1(StrEnum):
    approve = 'approve'
    reject = 'reject'


class SopDraftReviewRequest(BaseModel):
    decision: Decision1
    comment: str | None = Field(None, max_length=1000)


class SopDraftAdoptRequest(BaseModel):
    target_case_id: UUID | None = None
    """
    採納為現有案例的更新；省略則建立新案例
    """


class ResolveRequest(BaseModel):
    problem_card_id: UUID


class Layer(StrEnum):
    faq_match = 'faq_match'
    knowledge_base_rag = 'knowledge_base_rag'
    llm_generation = 'llm_generation'
    escalation = 'escalation'


class Type(StrEnum):
    case = 'case'
    manual = 'manual'


class Source1(BaseModel):
    type: Type | None = None
    id: UUID | None = None
    snippet: str | None = None
    score: float | None = None


class ResolveResponse(BaseModel):
    layer: Layer
    answer: str
    sources: list[Source1] | None = None
    confidence: float | None = Field(None, ge=0.0, le=1.0)


class AuthRefreshRequest(BaseModel):
    refresh_token: str


class AuthLogoutRequest(BaseModel):
    refresh_token: str | None = None


class ChangePasswordRequest(BaseModel):
    """
    變更密碼。new_password 至少 8 字元（與 bcrypt 72 byte 上限一致），
    且不可與 current_password 相同。

    """

    current_password: str = Field(..., max_length=72, min_length=8)
    new_password: str = Field(..., max_length=72, min_length=8)


class DashboardPeriod(StrEnum):
    today = 'today'
    field_7d = '7d'
    field_30d = '30d'
    field_90d = '90d'


class Conversations(BaseModel):
    total: int = Field(..., ge=0)
    active: int = Field(..., ge=0)
    resolved: int = Field(..., ge=0)
    escalated: int = Field(..., ge=0)


class Resolution(BaseModel):
    ai_resolution_rate: float | None = Field(None, ge=0.0, le=1.0)
    avg_resolution_time_seconds: int | None = Field(None, ge=0)
    by_layer: dict[str, int] | None = None


class HotTopic(BaseModel):
    topic: str | None = None
    count: int | None = Field(None, ge=0)


class TokenUsage(BaseModel):
    total_tokens: int | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    estimated_cost_usd: float | None = None


class TopBrand(BaseModel):
    brand: str | None = None
    count: int | None = Field(None, ge=0)


class WorkOrders(BaseModel):
    """
    派工今日 KPI（today_count / completion_rate / overdue_count）。
    """

    today_count: int | None = Field(None, ge=0)
    """
    今日新建工單數
    """
    completion_rate: float | None = Field(None, ge=0.0, le=1.0)
    """
    今日完工率 = 今日完工 / 今日新建（today_count == 0 時為 null）
    """
    overdue_count: int | None = Field(None, ge=0)
    """
    排程時間已過且未結案（status NOT IN completed/closed/cancelled）
    """


class Technicians(BaseModel):
    """
    技師概況 KPI（total_count / online_count / dispatchable_count）。
    """

    total_count: int | None = Field(None, ge=0)
    """
    此租戶啟用中（status='active'）的技師總數
    """
    online_count: int | None = Field(None, ge=0)
    """
    目前可派遣的技師數（active 且不在執行中工單）
    """
    dispatchable_count: int | None = Field(None, ge=0)
    """
    已上線且可立即指派（保留欄位，目前等同 online_count）
    """


class DashboardStats(BaseModel):
    period: DashboardPeriod
    conversations: Conversations
    resolution: Resolution
    hot_topics: list[HotTopic] | None = None
    token_usage: TokenUsage | None = None
    top_brands: list[TopBrand] | None = None
    work_orders: WorkOrders | None = None
    """
    派工今日 KPI（today_count / completion_rate / overdue_count）。
    """
    technicians: Technicians | None = None
    """
    技師概況 KPI（total_count / online_count / dispatchable_count）。
    """


class RevenueKpis(BaseModel):
    month_revenue: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    """
    本月營收（已開立 invoice issued + paid 加總，TWD 字串）
    """
    average_invoice_amount: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    """
    平均 invoice 金額
    """
    paid_rate: float = Field(..., ge=0.0, le=1.0)
    """
    付款成功率 = paid / (issued + paid + cancelled)；無發票時為 null
    """
    outstanding_amount: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    """
    未收帳款金額（DB status='draft' 加總）
    """
    outstanding_count: int = Field(..., ge=0)
    """
    未收帳款筆數
    """


class RevenueTrendPoint(BaseModel):
    period: str
    """
    期間標籤（例 2026-04）
    """
    revenue: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    """
    期間內已開立 invoice 金額（TWD 字串）
    """
    order_count: int = Field(..., ge=0)
    """
    期間內 invoice 筆數
    """


class RevenueByBrandPoint(BaseModel):
    brand: str
    revenue: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    share: float = Field(..., ge=0.0, le=1.0)
    """
    占總營收比例
    """


class Granularity(StrEnum):
    day = 'day'
    week = 'week'
    month = 'month'


class RevenueSummary(BaseModel):
    granularity: Granularity
    kpis: RevenueKpis
    trend: list[RevenueTrendPoint]
    by_brand: list[RevenueByBrandPoint]


class KpiFunnel(BaseModel):
    """
    轉換漏斗（值為計數，過濾條件以 created_at 落在 period 區間內）。
    - dispatched：work_orders.status IN (assigned, in_progress, completed, confirmed)
    - completed：work_orders.status IN (completed, confirmed)

    """

    conversations: int = Field(..., ge=0)
    problem_cards: int = Field(..., ge=0)
    work_orders: int = Field(..., ge=0)
    dispatched: int = Field(..., ge=0)
    completed: int = Field(..., ge=0)


class KpiDisputeRates(BaseModel):
    """
    異常率（分母為 period 區間內 work_orders 總數，分母為 0 時欄位為 null）。

    """

    refund_rate: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,4})?$')
    """
    退款率（refund_requests 數 / work_orders 總數）
    """
    warranty_claim_rate: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,4})?$')
    """
    保固索賠率（warranty_claims 數 / work_orders 總數）
    """
    dispute_rate: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,4})?$')
    """
    爭議升級率（disputes 數 / work_orders 總數）
    """


class KpiTechnicianEfficiency(BaseModel):
    """
    技師效率指標。avg_handle_minutes 取 period 區間內所有 status='completed/confirmed'
    且具備 started_at + completed_at 工單的平均值。

    """

    avg_handle_minutes: float | None = Field(None, ge=0.0)
    """
    平均處理時長（分鐘）；無樣本時 null
    """
    completed_count: int | None = Field(None, ge=0)


class KpiReport(BaseModel):
    period: DashboardPeriod
    generated_at: AwareDatetime
    funnel: KpiFunnel
    dispute_rates: KpiDisputeRates
    technician_efficiency: KpiTechnicianEfficiency
    notes: list[str] | None = None
    """
    暫不可計算的指標（SLA / NPS / 滿意度 / FTFR / 差評率）說明
    """


class Rag(BaseModel):
    similarity_threshold: float | None = Field(None, ge=0.0, le=1.0)
    max_results: int | None = Field(None, ge=1)
    chunk_size: int | None = Field(None, ge=1)
    chunk_overlap: int | None = Field(None, ge=0)


class Llm(BaseModel):
    model: str | None = None
    temperature: float | None = Field(None, ge=0.0, le=2.0)
    max_tokens: int | None = Field(None, ge=1)
    system_prompt_version: str | None = None


class Resolution1(BaseModel):
    faq_confidence_threshold: float | None = Field(None, ge=0.0, le=1.0)
    rag_confidence_threshold: float | None = Field(None, ge=0.0, le=1.0)
    auto_escalation_enabled: bool | None = None


class LineBot(BaseModel):
    greeting_message_enabled: bool | None = None
    max_conversation_turns: int | None = Field(None, ge=1)


class SystemConfig(BaseModel):
    """
    系統設定（部分更新）。各區塊允許獨立 PATCH，未指定的子鍵不變動。

    """

    rag: Rag | None = None
    llm: Llm | None = None
    resolution: Resolution1 | None = None
    line_bot: LineBot | None = None


class AuditLogType(StrEnum):
    api_call = 'api_call'
    llm_interaction = 'llm_interaction'
    rag_retrieval = 'rag_retrieval'
    admin_action = 'admin_action'
    agent_message = 'agent_message'


class AuditLogEntry(BaseModel):
    id: UUID
    log_type: AuditLogType
    actor_id: UUID | None = None
    action: str = Field(..., max_length=200)
    details: dict[str, Any] | None = None
    created_at: AwareDatetime


class AuditLogPage(CursorPage):
    items: list[AuditLogEntry] | None = None


class SentimentAlertStatus(StrEnum):
    pending = 'pending'
    acknowledged = 'acknowledged'
    resolved = 'resolved'


class SentimentLabel(StrEnum):
    negative = 'negative'
    very_negative = 'very_negative'
    neutral = 'neutral'
    positive = 'positive'


class SentimentAlert(BaseModel):
    id: UUID
    conversation_id: UUID
    consumer_message: str | None = Field(None, max_length=2000)
    sentiment_label: SentimentLabel
    confidence: float = Field(..., ge=0.0, le=1.0)
    detected_keywords: list[str] | None = None
    problem_card_id: UUID | None = None
    status: SentimentAlertStatus
    notified_admin_ids: list[UUID] | None = None
    admin_note: str | None = Field(None, max_length=1000)
    created_at: AwareDatetime


class SentimentAlertUpdateRequest(BaseModel):
    status: SentimentAlertStatus
    admin_note: str | None = Field(None, max_length=1000)


class SentimentAlertPage(CursorPage):
    items: list[SentimentAlert] | None = None


class FamilyReviewAction(StrEnum):
    approved = 'approved'
    rejected = 'rejected'


class FamilyReviewPendingItem(BaseModel):
    sop_draft_id: UUID
    title: str
    admin_reviewer: str | None = None
    admin_approved_at: AwareDatetime | None = None
    awaiting_family_review_since: AwareDatetime


class FamilyReviewPendingResponse(BaseModel):
    data: list[FamilyReviewPendingItem]


class FamilyReviewCreateRequest(BaseModel):
    sop_draft_id: UUID
    action: FamilyReviewAction
    comment: str | None = Field(None, max_length=1000)


class FamilyReview(BaseModel):
    id: UUID
    sop_draft_id: UUID
    action: FamilyReviewAction
    reviewer_id: UUID
    comment: str | None = None
    created_at: AwareDatetime


class FamilyReviewPage(CursorPage):
    items: list[FamilyReview] | None = None


class KbExportStatus(StrEnum):
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'


class Scope(StrEnum):
    all = 'all'
    cases_only = 'cases_only'
    manuals_only = 'manuals_only'


class KbExportRequest(BaseModel):
    scope: Scope | None = 'all'
    brand: str | None = None


class KbExportJob(BaseModel):
    job_id: UUID
    status: KbExportStatus
    download_url: AnyUrl | None = None
    item_count: int | None = Field(None, ge=0)
    created_at: AwareDatetime
    completed_at: AwareDatetime | None = None


class TechnicianRegisterRequest(BaseModel):
    name: str
    phone: str = Field(..., pattern='^09\\d{8}$')
    email: EmailStr
    password: SecretStr = Field(..., min_length=8)
    capabilities: list[str]
    regions: list[str]


class TechnicianProfile(Technician):
    email: EmailStr | None = None


class TechnicianProfileEnvelope(ApiResponseGeneric):
    data: TechnicianProfile | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class TechnicianUpdateRequest(BaseModel):
    name: str | None = None
    phone: str | None = Field(None, pattern='^09\\d{8}$')
    email: EmailStr | None = None
    capabilities: list[str] | None = None
    regions: list[str] | None = None


class WorkOrderConfirmRequest(BaseModel):
    rating: int = Field(..., ge=1, le=5)
    feedback: str | None = Field(None, max_length=1000)


class Urgency1(StrEnum):
    normal = 'normal'
    emergency = 'emergency'


class DispatchAutoMatchRequest(BaseModel):
    problem_card_id: UUID
    urgency: Urgency1 | None = 'normal'
    max_candidates: int | None = Field(3, ge=1, le=10)


class DispatchCandidate(BaseModel):
    technician_id: UUID
    technician_name: str | None = None
    score: float = Field(..., ge=0.0, le=1.0)
    distance_km: float | None = None
    eta_minutes: int | None = Field(None, ge=0)
    rating: float | None = Field(None, ge=0.0, le=5.0)


class DispatchAutoMatchResponse(BaseModel):
    candidates: list[DispatchCandidate]


class DispatchAssignRequest(BaseModel):
    """
    E5 §8.3：批次或顯式指派工單。`work_order_id` + `technician_id` 必填；
    與 `/api/v1/work-orders/{id}/assign` 之差異：本端點接受 body 中傳遞工單 id，
    適用於從候選列表批次派發。

    """

    work_order_id: UUID
    technician_id: UUID
    override_reason: str | None = Field(None, max_length=500)


class LockType(StrEnum):
    digital_deadbolt = 'digital_deadbolt'
    smart_lock = 'smart_lock'
    padlock = 'padlock'
    other = 'other'


class DifficultyLevel(StrEnum):
    simple = 'simple'
    moderate = 'moderate'
    complex = 'complex'


class PricingCalculateRequest(BaseModel):
    brand: str
    model: str | None = None
    lock_type: LockType
    difficulty: DifficultyLevel
    is_emergency: bool | None = False
    is_night_service: bool | None = False
    additional_items: list[str] | None = None


class PricingSurcharge(BaseModel):
    name: str
    condition: str | None = None
    amount: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')


class PricingCalculateResponse(BaseModel):
    base_price: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    surcharges: list[PricingSurcharge] | None = None
    total: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    currency: Currency | None = 'TWD'


class PricingRule(BaseModel):
    id: UUID
    brand: str
    lock_type: LockType
    difficulty: DifficultyLevel
    base_price: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    surcharges: list[PricingSurcharge] | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class PricingRuleCreateRequest(BaseModel):
    brand: str
    lock_type: LockType
    difficulty: DifficultyLevel
    base_price: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    surcharges: list[PricingSurcharge] | None = None


class PricingRuleUpdateRequest(BaseModel):
    base_price: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,2})?$')
    surcharges: list[PricingSurcharge] | None = None


class PricingRuleEnvelope(ApiResponseGeneric):
    data: PricingRule | None = None
    """
    實際載荷，由各 endpoint 具體化
    """


class PricingRulePage(CursorPage):
    items: list[PricingRule] | None = None


class ReconciliationStatus(StrEnum):
    pending = 'pending'
    approved = 'approved'
    disputed = 'disputed'


class Reconciliation(BaseModel):
    id: UUID
    technician_id: UUID
    technician_name: str | None = None
    period_start: AwareDatetime
    period_end: AwareDatetime
    total_orders: int = Field(..., ge=0)
    total_revenue: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    platform_fee: str | None = Field(None, pattern='^-?\\d+(\\.\\d{1,2})?$')
    technician_payout: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    status: ReconciliationStatus
    approved_by: UUID | None = None
    approved_at: AwareDatetime | None = None
    created_at: AwareDatetime


class ReconciliationApproveRequest(BaseModel):
    note: str | None = Field(None, max_length=500)


class ReconciliationPage(CursorPage):
    items: list[Reconciliation] | None = None


class SettlementStatus(StrEnum):
    pending = 'pending'
    paid = 'paid'
    failed = 'failed'


class PaymentMethod(StrEnum):
    bank_transfer = 'bank_transfer'
    other = 'other'


class Settlement(BaseModel):
    id: UUID
    reconciliation_id: UUID
    technician_id: UUID
    technician_name: str | None = None
    amount: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    currency: Currency
    status: SettlementStatus
    payment_method: PaymentMethod | None = None
    paid_at: AwareDatetime | None = None
    created_at: AwareDatetime


class SettlementPage(CursorPage):
    items: list[Settlement] | None = None


class RelatedEntityType(StrEnum):
    reconciliation = 'reconciliation'
    settlement = 'settlement'
    refund = 'refund'
    invoice = 'invoice'


class Voucher(BaseModel):
    """
    會計憑證（傳票），對應一筆對帳/結算/退款的雙分錄記錄。

    """

    id: UUID
    voucher_number: str
    related_entity_type: RelatedEntityType | None = None
    related_entity_id: UUID | None = None
    debit_account: str
    credit_account: str
    amount: str = Field(..., pattern='^-?\\d+(\\.\\d{1,2})?$')
    currency: Currency
    posting_date: date
    memo: str | None = None
    created_at: AwareDatetime


class VoucherPage(CursorPage):
    items: list[Voucher] | None = None


class TargetType(StrEnum):
    technician = 'technician'
    admin = 'admin'
    customer = 'customer'


class Channel(StrEnum):
    push = 'push'
    sms = 'sms'
    line = 'line'
    email = 'email'


class NotificationPushRequest(BaseModel):
    target_type: TargetType
    target_id: UUID
    type: NotificationType
    title: str = Field(..., max_length=200)
    body: str = Field(..., max_length=1000)
    data: dict[str, Any] | None = None
    channels: list[Channel] | None = None


class ApiErrorResponse(BaseModel):
    error_code: str = Field(
        ...,
        examples=[
            'VALIDATION_ERROR',
            'UNAUTHORIZED',
            'FORBIDDEN',
            'NOT_FOUND',
            'CONFLICT',
            'OPTIMISTIC_LOCK_FAILED',
            'RATE_LIMITED',
            'IDEMPOTENCY_KEY_REUSED',
            'TENANT_MISMATCH',
            'INTERNAL_ERROR',
            'SERVICE_UNAVAILABLE',
            'WORK_ORDER_CONFLICT',
            'WORK_ORDER_STATUS_INVALID',
            'QUOTE_EXPIRED',
            'TECHNICIAN_CIRCUIT_BREAKER_OPEN',
            'TECHNICIAN_SCHEDULE_CONFLICT',
            'DISPATCH_NO_TECHNICIAN_AVAILABLE',
            'DISPATCH_OVERRIDE_REQUIRED',
            'DISPATCH_REASON_MISSING',
            'SIGNATURE_ALREADY_SIGNED',
            'APPEARANCE_CHANGE_SIGNATURE_REJECTED',
            'APPEARANCE_CHANGE_EVIDENCE_INCOMPLETE',
            'REFUND_DUAL_SIGN_REQUIRED',
            'REFUND_DECISION_LOCKED',
            'COMPLAINT_ALREADY_IN_DISPUTE',
            'DISPUTE_MERGE_FAILED',
            'DISPUTE_EXTERNAL_PENDING',
            'DISPUTE_SLA_OVERDUE',
            'INVENTORY_INSUFFICIENT',
            'INVENTORY_PART_NOT_FOUND',
            'ROLE_IN_USE',
            'PERMISSION_CODE_INVALID',
            'AUDIT_EXPORT_TOO_LARGE',
            'DIAGNOSTIC_STREAM_CLOSED',
            'TENANT_SUSPENDED',
            'TENANT_LINE_BINDING_FAILED',
            'TENANT_NOT_FOUND',
            'BRAND_CONFIG_INVALID',
            'BRAND_REVIEW_PENDING',
            'TENANT_QUOTA_EXCEEDED',
            'NOTIFICATION_NOT_FOUND',
            'NOTIFICATION_BULK_LIMIT_EXCEEDED',
            'RESCHEDULE_LIMIT_EXCEEDED',
            'RESCHEDULE_RSVP_EXPIRED',
            'RESCHEDULE_SLOT_TAKEN',
        ],
    )
    """
    統一錯誤碼（見 `docs/02-design/error-codes.md`）
    """
    message: str
    """
    使用者可見訊息（依 Accept-Language i18n）
    """
    details: list[ApiFieldError] | None = None
